version: 0.0
os: linux
files:
  - source: Commands
    destination: /Instar/Commands
  - source: InstarBot/bin/Release/net6.0
    destination: /Instar/bin
hooks:
  ApplicationStart:
    - location: /Commands/ApplicationStart/StartInstar.sh
      timeout: 3600