version: 0.0
os: linux
files:
  - source: Commands
    destination: /Instar/Commands
  - source: InstarBot/bin/Release/net6.0
    destination: /Instar/bin
hooks:
  ApplicationStop:
    - location: /Instar/Commands/ApplicationStop/StopInstar.sh
      timeout: 3600
  AfterInstall:
    - location: /Instar/Commands/AfterInstall/DownloadConfig.sh
      timeout: 3600
  ApplicationStart:
    - location: /Instar/Commands/ApplicationStart/StartInstar.sh
      timeout: 3600
  ValidateService:
    - location: /Instar/Commands/ValidateService/CheckInstarRunning.sh
      timeout: 3600